name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.23
      uses: actions/setup-go@v2
      with:
        go-version: '1.23'
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi
    - name: Build
      run: go build -v .
    - name: Test
      run: |
          go test -v ./... -covermode=count -coverprofile=coverage.out
          go tool cover -func=coverage.out -o=coverage.out
    - name: Go Coverage Badge  # Pass the `coverage.out` output to this action
      uses: tj-actions/coverage-badge-go@v2
      with:
        filename: coverage.out
    - name: Verify Changed files
      uses: tj-actions/verify-changed-files@v20
      id: verify-changed-files
      with:
        files: README.md
    - name: Commit changes
      if: steps.verify-changed-files.outputs.files_changed == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add README.md
        git commit -m "chore: Updated coverage badge."

    - name: Push changes
      if: steps.verify-changed-files.outputs.files_changed == 'true'
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ github.token }}
        branch: ${{ github.head_ref }}